### ISSUE TITLE
Translate german documentation passages to english

### ISSUE THREAD

**Issue by mobo4b** [CaritasDeutschland/documentation#10]
**Does the proposed refactoring task solve a problem, reduce complexity or even improve performance? Please describe.**
The documentation is not translated completely in english.

**Describe the solution you'd like**
The following pages/passages need to be translated to english:

- documentation/docs/backend/build-and-load-docker-image.md
- documentation/docs/backend/create-core-data-import-users.md
- documentation/docs/backend/file-permissions.md
- documentation/docs/backend/first-start.md
- documentation/docs/backend/install-and-running-locally.md
- documentation/docs/backend/install-and-running-on-server.md
- documentation/docs/backend/jenkins.md
- documentation/docs/backend/liquibase.md
- documentation/docs/backend/login-data-access-links.md
- documentation/docs/backend/mailservice-templates.md
- documentation/docs/backend/openldap-configuration.md
- documentation/docs/backend/service-configuration.md
- documentation/docs/backend/ssl-certificate.md
- documentation/docs/backend/starting-and-stopping-the-services.md

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by ben10ben** [comment]
The translation should be finished soon. I will post something more specific when I know.
